# server config
server:
  port: 8080

spring:
  # DB config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Local Dev & Docker(Local) deploy
    #    url: jdbc:mysql://database-server:3306/naerodb
    url: jdbc:mysql://localhost:3306/naerodb
    username: naero
    password: naero

  # fileupload config
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB
  web:
    resources:
      static-locations: classpath:/naeroimgs/
  # JPA config
  jpa:
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

# static resource(image media file) config
## 이미지를 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  # Local Dev
  add-resource-locations: classpath:/static/naeroimgs/
  add-resource-handler: /naeroimgs/**
  # Local Dev
  image-dir: src/main/resources/static/naeroimgs
  image-url: http://localhost:8080/naeroimgs/
  # Docker(Local)
  #  add-resource-locations: file:///springboot-app/naeroimgs/
  #  add-resource-handler: /naeroimgs/**
  # Docker(Local)
#  image-dir: /springboot-app/naeroimgs
#  image-url: http://localhost:8080/naeroimgs/

# springdoc open-api config
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# logging config
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
