server:
  port: 8080

spring:
  # DB config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/naerodb
    username: naero
    password: naero
  
  # JPA config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  # File upload config
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB
  
  # Static resource config
  web:
    resources:
      static-locations: classpath:/productimgs/
