# 로그인 기능 막아둠
spring:
#  데이터베이스
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/naerodb
    username: naero
    password: naero
  # fileupload config
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 1MB
  web:
    resources:
      static-locations: classpath:/naeroimgs/
  # JPA config
  jpa:
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

# static resource(image media file) config
## 이미지를 저장할 위치와 응답할 때 이미지 주소 세팅
image:
  add-resource-locations: file:///springboot-app/naeroimgs/
  add-resource-handler: /naeroimgs/**
  # Docker(Local)
  image-dir: /springboot-app/naeroimgs
  image-url: http://localhost:8080/naeroimgs/
